# Generated by Django 3.2 on 2022-01-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0004_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='product_color',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
