# Generated by Django 3.2 on 2022-01-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_id', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(max_length=254)),
                ('brand', models.CharField(blank=True, max_length=254, null=True)),
                ('image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('product_colors', models.JSONField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_sign', models.CharField(blank=True, max_length=254, null=True)),
                ('currency', models.CharField(blank=True, max_length=254, null=True)),
                ('product_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('website_link', models.URLField(blank=True, max_length=1024, null=True)),
                ('rating', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('type_category', models.CharField(blank=True, max_length=254, null=True)),
                ('tag_list', models.JSONField(blank=True, null=True)),
                ('created_at', models.CharField(blank=True, max_length=500, null=True)),
                ('updated_at', models.CharField(blank=True, max_length=500, null=True)),
                ('product_api_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('api_featured_image', models.URLField(blank=True, max_length=1024, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
            ],
        ),
    ]
