# Generated by Django 3.2 on 2022-01-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='number_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
